### ISSUE TITLE
[BUG] redirect to login loosing secure connection

### ISSUE THREAD

**Issue by vitorbari** [brnbp/podty#23]
Navigating as guest, when I try to access an page that requires authentication, the application redirects me to `/login` with http protocol, even though I was in a https page.

![image](https://user-images.githubusercontent.com/1184252/32581004-426d7e9a-c4cf-11e7-834e-9d9522eb2dc3.png)

**Comment by ejosess** [comment]
+1

**Comment by brnbp** [comment]
@vitorbari Thanks for reporting! I'm just fixed that. ref #24
